export const BACKGROUND_IMAGE_SET_BLUE_50 = "BACKGROUND_IMAGE/SET_BLUE_50";
export const BACKGROUND_IMAGE_SET_BLUE_60 = "BACKGROUND_IMAGE/SET_BLUE_60";
export const BACKGROUND_IMAGE_SET_BLUE_70 = "BACKGROUND_IMAGE/SET_BLUE_70";
export const BACKGROUND_IMAGE_SET_DARK_BLUE_30 =
  "BACKGROUND_IMAGE/SET_DARK_BLUE_30";
export const BACKGROUND_IMAGE_SET_DARK_BLUE_50 =
  "BACKGROUND_IMAGE/SET_DARK_BLUE_50";
export const BACKGROUND_IMAGE_SET_DARK_BLUE_70 =
  "BACKGROUND_IMAGE/SET_DARK_BLUE_70";
export const BACKGROUND_IMAGE_SET_GREEN_50 = "BACKGROUND_IMAGE/SET_GREEN_50";
export const BACKGROUND_IMAGE_SET_GREEN_60 = "BACKGROUND_IMAGE/SET_GREEN_60";
export const BACKGROUND_IMAGE_SET_GREEN_70 = "BACKGROUND_IMAGE/SET_GREEN_70";
export const BACKGROUND_IMAGE_SET_GREY_40 = "BACKGROUND_IMAGE/SET_GREY_40";
export const BACKGROUND_IMAGE_SET_GREY_70 = "BACKGROUND_IMAGE/SET_GREY_70";
export const BACKGROUND_IMAGE_SET_GREY_80 = "BACKGROUND_IMAGE/SET_GREY_80";
export const BACKGROUND_IMAGE_SET_RED_50 = "BACKGROUND_IMAGE/SET_RED_50";
export const BACKGROUND_IMAGE_SET_RED_60 = "BACKGROUND_IMAGE/SET_RED_60";
export const BACKGROUND_IMAGE_SET_RED_70 = "BACKGROUND_IMAGE/SET_RED_70";
export const BACKGROUND_IMAGE_SET_YELLOW_50 = "BACKGROUND_IMAGE/SET_YELLOW_50";
export const BACKGROUND_IMAGE_SET_YELLOW_60 = "BACKGROUND_IMAGE/SET_YELLOW_60";
export const BACKGROUND_IMAGE_SET_YELLOW_70 = "BACKGROUND_IMAGE/SET_YELLOW_70";

export const ACCESSORIZE_SET_HAIR = "ACCESSORIZE/SET_HAIR";
export const ACCESSORIZE_SET_EARS = "ACCESSORIZE/SET_EARS";
export const ACCESSORIZE_SET_EYES = "ACCESSORIZE/SET_EYES";
export const ACCESSORIZE_SET_MOUTH = "ACCESSORIZE/SET_MOUTH";
export const ACCESSORIZE_SET_NECK = "ACCESSORIZE/SET_NECK";
export const ACCESSORIZE_SET_LEG = "ACCESSORIZE/SET_LEG";
export const ACCESSORIZE_SET_ACCESSORIES = "ACCESSORIZE/SET_ACCESSORIES";
export const ACCESSORIZE_SET_BACKGROUND = "ACCESSORIZE/SET_BACKGROUND";
