export const BACKGROUND_IMAGE_SET_BLUE_50 = "BACKGROUND_IMAGE/SET_BLUE_50";
export const BACKGROUND_IMAGE_SET_BLUE_60 = "BACKGROUND_IMAGE/SET_BLUE_60";
export const BACKGROUND_IMAGE_SET_BLUE_70 = "BACKGROUND_IMAGE/SET_BLUE_70";
export const BACKGROUND_IMAGE_SET_DARK_BLUE_30 =
  "BACKGROUND_IMAGE/SET_DARK_BLUE_30";
export const BACKGROUND_IMAGE_SET_DARK_BLUE_50 =
  "BACKGROUND_IMAGE/SET_DARK_BLUE_50";
export const BACKGROUND_IMAGE_SET_DARK_BLUE_70 =
  "BACKGROUND_IMAGE/SET_DARK_BLUE_70";
export const BACKGROUND_IMAGE_SET_GREEN_50 = "BACKGROUND_IMAGE/SET_GREEN_50";
export const BACKGROUND_IMAGE_SET_GREEN_60 = "BACKGROUND_IMAGE/SET_GREEN_60";
export const BACKGROUND_IMAGE_SET_GREEN_70 = "BACKGROUND_IMAGE/SET_GREEN_70";
export const BACKGROUND_IMAGE_SET_GREY_40 = "BACKGROUND_IMAGE/SET_GREY_40";
export const BACKGROUND_IMAGE_SET_GREY_70 = "BACKGROUND_IMAGE/SET_GREY_70";
export const BACKGROUND_IMAGE_SET_GREY_80 = "BACKGROUND_IMAGE/SET_GREY_80";
export const BACKGROUND_IMAGE_SET_RED_50 = "BACKGROUND_IMAGE/SET_RED_50";
export const BACKGROUND_IMAGE_SET_RED_60 = "BACKGROUND_IMAGE/SET_RED_60";
export const BACKGROUND_IMAGE_SET_RED_70 = "BACKGROUND_IMAGE/SET_RED_70";
export const BACKGROUND_IMAGE_SET_YELLOW_50 = "BACKGROUND_IMAGE/SET_YELLOW_50";
export const BACKGROUND_IMAGE_SET_YELLOW_60 = "BACKGROUND_IMAGE/SET_YELLOW_60";
export const BACKGROUND_IMAGE_SET_YELLOW_70 = "BACKGROUND_IMAGE/SET_YELLOW_70";

export const ACCESSORIZE_SET_HAIR = "ACCESSORIZE/SET_HAIR";
export const ACCESSORIZE_SET_EARS = "ACCESSORIZE/SET_EARS";
export const ACCESSORIZE_SET_EYES = "ACCESSORIZE/SET_EYES";
export const ACCESSORIZE_SET_MOUTH = "ACCESSORIZE/SET_MOUTH";
export const ACCESSORIZE_SET_NECK = "ACCESSORIZE/SET_NECK";
export const ACCESSORIZE_SET_LEG = "ACCESSORIZE/SET_LEG";
export const ACCESSORIZE_SET_ACCESSORIES = "ACCESSORIZE/SET_ACCESSORIES";
export const ACCESSORIZE_SET_BACKGROUND = "ACCESSORIZE/SET_BACKGROUND";

export const STYLE_SET_HAIR_DEFAULT = "STYLE/HAIR_DEFAULT";
export const STYLE_SET_HAIR_BANG = "STYLE/HAIR_BANG";
export const STYLE_SET_HAIR_CURLS = "STYLE/HARI_CURLS";
export const STYLE_SET_HAIR_ELEGANT = "STYLE/HAIR_ELEGANT";
export const STYLE_SET_HAIR_FANCY = "STYLE/HAIR_FANCY";
export const STYLE_SET_HAIR_QUIFF = "STYLE/HAIR_QUIFF";
export const STYLE_SET_HAIR_SHORT = "STYLE/HAIR_SHORT";

export const STYLE_SET_EARS_DEFAULT = "STYLE/EARS_DEFAULT";
export const STYLE_SET_EARS_TILT_BACKWARD = "STYLE/EARS_TILT_BACKWARD";
export const STYLE_SET_EARS_TILT_FORWARD = "STYLE/EARS_TILT_FORWARD";

export const STYLE_SET_EYES_ANGRY = "STYLE/EYES_ANGRY";
export const STYLE_SET_EYES_DEFAULT = "STYLE/EYES_DEFAULT";
export const STYLE_SET_EYES_NAUGHTY = "STYLE/EYES_NAUGHTY";
export const STYLE_SET_EYES_PANDA = "STYLE/EYES_PANDA";
export const STYLE_SET_EYES_SMART = "STYLE/EYES_SMART";
export const STYLE_SET_EYES_STAR = "STYLE/EYES_STAR";

export const STYLE_SET_MOUTH_DEFAULT = "STYLE/MOUTH_DEFAULT";
export const STYLE_SET_MOUTH_ASTONISHED = "STYLE/MOUTH_ASTONISHED";
export const STYLE_SET_MOUTH_EATING = "STYLE/MOUTH_EARTING";
export const STYLE_SET_MOUTH_LAUGH = "STYLE/MOUTH_LAUGH";
export const STYLE_SET_MOUTH_TONGUE = "STYLE/MOUGHT_TONGUE";

export const STYLE_SET_NECK_DEFAULT = "STYLE/NECK_DEFAULT";
export const STYLE_SET_NECK_BEND_BACKWARD = "STYLE/NECK_BEND_BACKWARD";
export const STYLE_SET_NECK_BEND_FORWARD = "STYLE/NECK_BEND_FORWARD";
export const STYLE_SET_NECK_THICK = "STYLE/NECK_THICK";

export const STYLE_SET_LEG_DEFAULT = "STYLE/LEG_DEFAULT";
export const STYLE_SET_LEG_BUBBLE_TEA = "STYLE/LEG_BUBBLE_TEA";
export const STYLE_SET_LEG_COOKIE = "STYLE/LEG_COOKIE";
export const STYLE_SET_LEG_GAME_CONSOLE = "STYLE/LEG_GAME_CONSOLE";
export const STYLE_SET_LEG_TILT_BACKWARD = "STYLE/LEG_TILT_BACKWARD";
export const STYLE_SET_LEG_TILT_FORWARD = "STYLE/LEG_TILT_FORWARD";
